# Generated by Django 4.0.1 on 2022-01-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Производитель')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='CraneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Код крана')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Кран',
                'verbose_name_plural': 'Краны',
            },
        ),
    ]
